#![forbid(unsafe_code)]

//! Fast, safe, streaming AES Crypt (v0–v3) encryption and decryption.
//!
//! `aescrypt-rs` reads every published AES Crypt file format version (v0–v3) and writes
//! the modern v3 format only. The public surface is intentionally small — most users
//! only need [`encrypt()`], [`decrypt()`], and [`read_version()`] — but the lower-level
//! KDF, header, session, and streaming primitives are exposed for custom flows.
//!
//! # Quick Start
//!
//! Encrypt and decrypt data using AES Crypt format v3:
//!
//! ```rust,no_run
//! use aescrypt_rs::{encrypt, decrypt, constants::DEFAULT_PBKDF2_ITERATIONS};
//! use std::io::Cursor;
//!
//! let password = "correct horse battery staple";
//! let data = b"top secret";
//!
//! // Encrypt
//! let mut ciphertext = Vec::new();
//! encrypt(Cursor::new(data), &mut ciphertext, password, DEFAULT_PBKDF2_ITERATIONS)?;
//!
//! // Decrypt
//! let mut plaintext = Vec::new();
//! decrypt(Cursor::new(&ciphertext), &mut plaintext, password)?;
//!
//! assert_eq!(data, &plaintext[..]);
//! # Ok::<(), aescrypt_rs::AescryptError>(())
//! ```
//!
//! Passwords are ordinary `&str` borrows, so the crate composes with whatever
//! zeroize-on-drop container you already use. Keep the secret wrapped and hand
//! the API a scoped borrow:
//!
//! ```rust,no_run
//! use aescrypt_rs::{encrypt, aliases::PasswordString, constants::DEFAULT_PBKDF2_ITERATIONS};
//! use secure_gate::RevealSecret;
//! use std::io::Cursor;
//!
//! let secret = PasswordString::new("correct horse battery staple".to_string());
//! let mut ciphertext = Vec::new();
//!
//! // caller keeps the secret wrapped; the borrow never escapes
//! secret.with_secret(|pw| {
//!     encrypt(Cursor::new(b"top secret"), &mut ciphertext, pw, DEFAULT_PBKDF2_ITERATIONS)
//! })?;
//! # Ok::<(), aescrypt_rs::AescryptError>(())
//! ```
//!
//! Detect file format version without decrypting:
//!
//! ```rust
//! use aescrypt_rs::read_version;
//! use std::io::Cursor;
//!
//! let header = b"AES\x03\x00";
//! let version = read_version(Cursor::new(header))?;
//! assert_eq!(version, 3);
//! # Ok::<(), aescrypt_rs::AescryptError>(())
//! ```
//!
//! # Supported Formats
//!
//! | Operation        | v0  | v1  | v2  | v3  |
//! | ---------------- | :-: | :-: | :-: | :-: |
//! | [`decrypt()`]    |  Y  |  Y  |  Y  |  Y  |
//! | [`encrypt()`]    |  –  |  –  |  –  |  Y  |
//! | [`read_version()`] |  Y  |  Y  |  Y  |  Y  |
//!
//! v3 is the only format produced on write. v0–v2 are read-only for compatibility with
//! files generated by older AES Crypt tools.
//!
//! # Feature Flags
//!
//! This crate defines **no Cargo features**. The following dependency feature flags
//! are always enabled and cannot be disabled by downstream crates:
//!
//! - `aes/zeroize` — automatic zeroization of AES round keys on drop.
//! - `secure-gate/rand` — CSPRNG-backed random IV/key/salt generation.
//! - `secure-gate/ct-eq` — constant-time HMAC and PKCS#7 padding comparisons.
//!
//! Building with `--no-default-features` is a no-op; the security posture is fixed.
//!
//! # MSRV
//!
//! Minimum Supported Rust Version is **1.85** (edition 2021). CI verifies the crate
//! against `cargo +1.85 test --all-features` and `cargo +1.85 bench --no-run`.
//!
//! # Security Model
//!
//! - **No `unsafe` in this crate** — enforced by `#![forbid(unsafe_code)]`. Cryptographic
//!   backends and `secure-gate` may use `unsafe` internally; this crate does not.
//! - **Key derivation**: PBKDF2-HMAC-SHA512 for v3 (caller-controlled iterations,
//!   default [`DEFAULT_PBKDF2_ITERATIONS`](constants::DEFAULT_PBKDF2_ITERATIONS) = 300 000),
//!   and the AES Crypt v0–v2 ACKDF (8192 SHA-256 iterations, UTF-16-LE password) for legacy reads.
//! - **Bulk encryption**: AES-256-CBC with PKCS#7 padding (v3) or legacy modulo padding
//!   (v0/v1/v2 read-only).
//! - **Authentication**: HMAC-SHA256 over the encrypted session block and ciphertext
//!   stream. Session and payload tags are compared with constant-time equality.
//! - **Memory hygiene**: every key, IV, salt, and intermediate buffer this crate
//!   *creates* is wrapped in a [`secure-gate`] type
//!   ([`Aes256Key32`](aliases::Aes256Key32), [`Iv16`](aliases::Iv16),
//!   [`Salt16`](aliases::Salt16), …) that zeroizes on drop. Two categories sit
//!   outside that guarantee:
//!   - The **password**: it enters the crate as a `&str` borrow, is read in place,
//!     and is never copied or stored — so zeroizing it is the caller's
//!     responsibility. See [Password ownership](#password-ownership) below.
//!   - **Third-party cipher and hasher internals**, which this crate cannot reach.
//!     `aes` is built with its `zeroize` feature, so the AES key schedule *is*
//!     wiped on drop. `hmac` 0.12 and `sha2` 0.10 expose no zeroize hook at all:
//!     the HMAC opad/ipad state — derived from the setup, session and payload keys
//!     — and the SHA-256 chaining state and block buffer persist until their stack
//!     frames are reused. Recovering a key from that state is preimage-hard, but
//!     HMAC state is sufficient to forge tags under the key it was built from. This
//!     is a property of those crates, not a gap this crate can close.
//! - **Decrypt-then-verify**: as defined by the AES Crypt format, the v3 payload HMAC
//!   is verified **after** the ciphertext stream is decrypted. [`decrypt()`] therefore
//!   may write partial unauthenticated plaintext to its `output` before returning an
//!   error — see [`decrypt()`] for the mandatory caller contract.
//! - **Legacy v0–v2 length malleability**: the final-block length ("modulo") byte —
//!   the 5th header byte for v0, the trailer byte for v1/v2 — is not covered by any
//!   HMAC. This is inherent to the original AES Crypt v0–v2 wire format and cannot be
//!   fixed by a conforming reader: a tampered legacy file can silently gain or lose up
//!   to 15 trailing plaintext bytes and still verify. v3 is not affected (plaintext
//!   length is recovered from PKCS#7 padding inside the authenticated ciphertext);
//!   re-encrypt legacy files as v3 if this matters to you.
//! - **PBKDF2 iteration bounds**: enforced by the encryption path to
//!   `[`PBKDF2_MIN_ITER`](constants::PBKDF2_MIN_ITER) ..= [`PBKDF2_MAX_ITER`](constants::PBKDF2_MAX_ITER)`.
//!   Lowering iterations weakens password resistance; do not go below
//!   [`DEFAULT_PBKDF2_ITERATIONS`](constants::DEFAULT_PBKDF2_ITERATIONS).
//!
//! # Password ownership
//!
//! [`encrypt()`], [`decrypt()`], [`derive_ackdf_key()`], [`derive_pbkdf2_key()`],
//! [`encryption::derive_setup_key()`] and [`Pbkdf2Builder::derive_secure()`] all take
//! the password as `&str`. Nothing on that path copies it: the borrow reaches
//! `pbkdf2`/`sha2` as `str::as_bytes()` and stops there. That means:
//!
//! - **The caller owns the password's lifetime and its zeroization.** Hold it in a
//!   zeroize-on-drop container ([`aliases::PasswordString`], `zeroize::Zeroizing`,
//!   or your own) and pass a scoped borrow, as in the Quick Start above.
//! - Values *derived* from the password inside this crate are still wrapped: the
//!   UTF-16-LE expansion in [`derive_ackdf_key()`] is a `secure_gate::Dynamic<Vec<u8>>`,
//!   and every derived key lands directly in a [`secure-gate`] alias.
//!
//! # Dependency coupling
//!
//! No `secure-gate` type appears in any signature a consumer must name, so this
//! crate's `secure-gate` version is an **internal** implementation detail: a
//! downstream crate can depend on a different `secure-gate` version without a type
//! mismatch, exactly like `odf-crypto`, `msoffice-crypto`, and `age-hpke-pq`.
//!
//! That property is opt-out, not absolute. The lower-level primitives in
//! [`encryption`], [`decryption`], and [`kdf`] — [`encryption::encrypt_stream()`],
//! [`decryption::extract_session_data()`], [`decryption::decrypt_ciphertext_stream()`],
//! [`decryption::read_exact_span()`], [`encryption::write_public_iv()`], and friends —
//! exchange [`aliases`] types by design, for callers driving the format stage by
//! stage. **Naming anything from [`aliases`] (or calling a function that does)
//! re-acquires the `secure-gate` version coupling**: your crate and this one must
//! then resolve to the same `secure-gate` version, because two versions produce two
//! distinct types with identical names. If that matters to you, stay on
//! [`encrypt()`] / [`decrypt()`] / the KDFs and the coupling never appears.
//!
//! # Errors
//!
//! Every fallible operation in this crate returns
//! [`Result<T, AescryptError>`](AescryptError). The error variants are documented on
//! [`AescryptError`] together with the public APIs that produce each variant.
//!
//! [`secure-gate`]: https://github.com/Slurp9187/secure-gate

pub mod aliases;
pub mod constants;
pub mod decryption;
pub mod encryption;
pub mod error;
pub mod header;
pub mod kdf;
pub mod pbkdf2_builder;
pub mod utilities;

// High-level API — this is what 99% of users import.
//
// Note: `PasswordString` is deliberately *not* re-exported here. It is a
// `secure-gate` type; keeping it behind `aliases::` keeps the crate root free of
// the version coupling described in the crate-level "Dependency coupling"
// section. Callers who want it can still `use aescrypt_rs::aliases::PasswordString`.
pub use decryption::decrypt;
pub use encryption::encrypt;
pub use error::AescryptError;

// Low-level KDFs — intentionally public at the root because:
// • They are needed for custom decryption flows (e.g. reading v0–v2 files without the high-level API).
// • They are the only non-wrapper crypto functions users ever need directly.
// • Keeping them at the root is the established pattern in the ecosystem (see `ring`, `password-hash`, etc.).
pub use pbkdf2_builder::Pbkdf2Builder;

pub use kdf::ackdf::derive_ackdf_key;
pub use kdf::pbkdf2::derive_pbkdf2_key;

// Header-only inspection.
pub use header::read_version;

// The README's examples are compiled and run by `cargo test --doc`, so they cannot
// silently rot. `cfg(doctest)` is set only while rustdoc *collects doctests* — never
// while it *builds documentation* — so this item never reaches docs.rs or `cargo doc`
// output, and the README is not duplicated onto the crate page, which already covers
// the same ground in the `//!` docs above.
//
// No feature gate is needed here: this crate defines no optional features, so the
// README's imports are always available.
//
// It must live at the end of the file: an item here would otherwise sit ahead of the
// `//!` crate docs above, which is not allowed.
//
// This is load-bearing rather than decorative. It was commented out until
// 0.2.0-rc.11, and in that time the "Advanced API Access" example drifted — it bound
// `read_file_version`'s `(u8, u8)` return as a single `u8` and had stopped compiling,
// with nothing to catch it.
#[cfg(doctest)]
#[doc = include_str!("../README.md")]
pub struct ReadmeDoctests;
